apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: samordning-personoppslag-q1
  namespace: pensjonsamhandling
  labels:
    team: pensjonsamhandling
spec:
  azure:
    application:
      enabled: true
      allowAllUsers: true
  accessPolicy:
    inbound:
      rules:
        - application: sam-q1
          namespace: pensjonsamhandling
          cluster: dev-fss

        - application: sambatch-q1
          namespace: pensjon-batch
          cluster: dev-fss

        - application: sam-q5
          namespace: pensjonsamhandling
          cluster: dev-fss

        - application: sambatch-q5
          namespace: pensjon-batch
          cluster: dev-fss

        - application: azure-token-generator
          namespace: aura
          cluster: dev-gcp

  image: {{ image }}
  port: 8080
  ingresses:
    - https://samordning-personoppslag-q1.dev.intern.nav.no
  secureLogs:
    enabled: false
  prometheus:
    enabled: true
    path: actuator/prometheus
  liveness:
    path: actuator/health/liveness
    initialDelay: 30
  readiness:
    path: actuator/health/readiness
    initialDelay: 30
  startup:
    path: actuator/health/readiness
    initialDelay: 30
    failureThreshold: 30
    periodSeconds: 5
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 80
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 200m
      memory: 500Mi
  vault:
    enabled: false
  webproxy: true
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: dev, q1
    - name: ENV
      value: q1
    - name: "OTEL_RESOURCE_ATTRIBUTES"
      value: "deployment.environment.name=q1"
    - name: PDL_URL
      value: https://pdl-api-q1.intern.dev.nav.no/graphql
    - name: PDL_SCOPE
      value: api://dev-fss.pdl.pdl-api-q1/.default
    - name: KODEVERK_URL
      value: https://kodeverk-api.intern.nav.no
    - name: KODEVERK_SCOPE
      value: api//dev-gcp.felleskodeverk-api/.default
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
      destinations:
        - id: grafana-lgtm
        - id: elastic-apm
