apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: samordning-personoppslag-q1
  namespace: pensjonsamhandling
  labels:
    team: pensjonsamhandling
spec:
  azure:
    application:
      enabled: true
      allowAllUsers: true
      claims:
        extra:
          - "NAVident"
          - "azp_name"
  accessPolicy:
    inbound:
      rules:
        - application: sam-q1
          namespace: pensjonsamhandling
          cluster: dev-fss
        - application: sambatch-q1
          namespace: pensjon-batch
          cluster: "dev-fss"
  image: {{ image }}
  port: 8080
  ingresses:
    - "https://samordning-personoppslag-q1.dev.intern.nav.no"
  secureLogs:
    enabled: false
  prometheus:
    enabled: true
    path: actuator/prometheus
  liveness:
    path: actuator/health/liveness
    initialDelay: 30
  readiness:
    path: actuator/health/readiness
    initialDelay: 30
  startup:
    path: actuator/health/readiness
    initialDelay: 30
    failureThreshold: 30
    periodSeconds: 5
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 80
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 200m
      memory: 500m
  vault:
    enabled: false
  webproxy: false
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: dev
    - name: ENV
      value: q2
    - name: "OTEL_RESOURCE_ATTRIBUTES"
      value: "deployment.environment.name=q2"
    - name: PDL_URL
      value: https://pdl-api-q1.intern.dev.nav.no/graphql
    - name: PDL_SCOPE
      value: api://dev-fss.pdl.pdl-q1-api/.default
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
      destinations:
        - id: grafana-lgtm
        - id: elastic-apm
