apiVersion: krakend.nais.io/v1
kind: ApiEndpoints
metadata:
  name: samordning-personoppslag-adresse
  namespace: pensjonsamhandling
  labels:
    team: pensjonsamhandling
spec:
  krakend: samordning-personoppslag
  auth:
    name: maskinporten
    cache: true
    scopes:
      - nav:pensjon/v1/samordning
  rateLimit:
    maxRate: 100
    clientMaxRate: 200
    every: 60s
  endpoints:
    - path: /api/adresse
      method: POST
      timeout: 60s
      forwardHeaders:
        - Authorization
        - Content-Type
        - X-Request-Id
        - fnr
      backendHost: https://samordning-personoppslag-q2.dev-fss-pub.nais.io
      backendPath: /api/adresse
