apiVersion: krakend.nais.io/v1
kind: ApiEndpoints
metadata:
    name: samordning-person
    namespace: pensjonsamhandling
    labels:
        team: pensjonsamhandling
spec:
    krakend: samordning-personoppslag
    auth:
        name: maskinporten
        cache: true
        scopes:
            - nav:pensjon/v1/samordning
    rateLimit:
        maxRate: 500
        clientMaxRate: 400
        every: 60s
    endpoints:
        - path: /api/person/post
          method: POST
          timeout: 60s
          forwardHeaders:
              - Authorization
              - Content-Type
              - X-Request-Id
              - fnr
          backendHost: https://samordning-personoppslag-q2.dev.intern.nav.no
          backendPath: /api/person
