no.nav.security.jwt:
  issuer:
    entraid:
      discovery-url: ${AZURE_APP_WELL_KNOWN_URL}
      accepted-audience: ${AZURE_APP_CLIENT_ID}

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BROKERS}
    security.protocol: SSL

    ssl:
      key-store-type: PKCS12
      key-store-location: file:${KAFKA_KEYSTORE_PATH}
      key-password: ${KAFKA_CREDSTORE_PASSWORD}
      trust-store-type: JKS
      trust-store-location: file:${KAFKA_TRUSTSTORE_PATH}
      trust-store-password: ${KAFKA_CREDSTORE_PASSWORD}

    properties:
      schema:
        registry:
          url: ${KAFKA_SCHEMA_REGISTRY}
      basic:
        auth:
          credentials:
            source: USER_INFO
          user:
            info: ${KAFKA_SCHEMA_REGISTRY_USER}:${KAFKA_SCHEMA_REGISTRY_PASSWORD}
    listener:
      ack-mode: manual

management:
  endpoint:
    health:
      show-details: always
      access: read_only
    metrics:
      access: read_only
    prometheus:
      access: read_only
  endpoints:
    web:
      exposure:
        include: prometheus, health, info, metrics
